'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { createContext, useState, useEffect } from 'react'
import { UserContext } from '../../utils/userContext'
import { getAuthUser } from '../../actions/user'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [user, setUser] = useState(false);

  useEffect(() => {
    const fetchData = async () => {

      const authUserResult = await getAuthUser();
      if (authUserResult.data.success === true) {
        setUser(authUserResult.data.success)
      }

    };
    fetchData();
  })

  return (
    <html lang="en">
      <UserContext.Provider value={{user,setUser}} >
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </UserContext.Provider>
    </html>
  )
}
